### ISSUE TITLE
Wrong Data / Data is not plausible

### ISSUE THREAD

**Issue by bonkersGER** [galexrt/srcds_exporter#7]
The exporter delivers data that is not plausible.

Examples:

Map="Max Players"
srcds_playercount_humans=83
srcds_playercount_limit=245
srcds_playercount_bots=66

```
`# HELP srcds_map The current map on the server.
# TYPE srcds_map gauge
srcds_map{map="Max Players",server="192.168.1.152:27015"} 1
srcds_map{map="de_dust2",server="192.168.1.153:27015"} 1
# HELP srcds_playercount_bots The current count of bot players on the server.
# TYPE srcds_playercount_bots gauge
srcds_playercount_bots{server="192.168.1.152:27015"} 66
srcds_playercount_bots{server="192.168.1.153:27015"} 0
# HELP srcds_playercount_current The current count players on the server.
# TYPE srcds_playercount_current gauge
srcds_playercount_current{server="192.168.1.152:27015"} 83
srcds_playercount_current{server="192.168.1.153:27015"} 0
# HELP srcds_playercount_humans The current count of humans players on the server.
# TYPE srcds_playercount_humans gauge
srcds_playercount_humans{server="192.168.1.152:27015"} 83
srcds_playercount_humans{server="192.168.1.153:27015"} 0
# HELP srcds_playercount_limit The limit of players on the server.
# TYPE srcds_playercount_limit gauge
srcds_playercount_limit{server="192.168.1.152:27015"} 245
srcds_playercount_limit{server="192.168.1.153:27015"} 20
# HELP srcds_scrape_collector_duration_seconds srcds_exporter: Duration of a collector scrape.
# TYPE srcds_scrape_collector_duration_seconds gauge
srcds_scrape_collector_duration_seconds{collector="map"} 3.2361e-05
srcds_scrape_collector_duration_seconds{collector="playercount"} 2.5077e-05
srcds_scrape_collector_duration_seconds{collector="players"} 6.292e-06
# HELP srcds_scrape_collector_success srcds_exporter: Whether a collector succeeded.
# TYPE srcds_scrape_collector_success gauge
srcds_scrape_collector_success{collector="map"} 1
srcds_scrape_collector_success{collector="playercount"} 1
srcds_scrape_collector_success{collector="players"} 1`
```

**Comment by galexrt** [comment]
What game are you running the exporter against? Post the `status` command output of the gameserver.

**Comment by bonkersGER** [comment]
I am running CS GO

] rcon status
hostname: Counter-Strike: Global Offensive
version : 1.38.5.5/13855 1547/8853 secure  [G:1:6214660] 
udp/ip  : 0.0.0.0:27015  (public ip: 78.46.103.122)
os      :  Linux
type    :  community dedicated
map     : de_dust2
players : 1 humans, 9 bots (20/0 max) (not hibernating)

# userid name uniqueid connected ping loss state rate adr
# 22 1 "bonkers" STEAM_1:1:XXXXXXX 00:29 46 0 active 128000 77.23.XXX.XXX:27005
#23 "Dustin" BOT active 128
#24 "Mike" BOT active 128
#25 "Ethan" BOT active 128
#26 "Calvin" BOT active 128
#27 "Shawn" BOT active 128
#28 "Gary" BOT active 128
#29 "Grant" BOT active 128
#30 "Irving" BOT active 128
#31 "Mark" BOT active 128
#end

**Comment by galexrt** [comment]
Which version/ commit of the exporter are you running?

**Comment by bonkersGER** [comment]
**srcds.example.yml** 

```
---
options:
  connectTimeout: 5s
  cacheExpiration: 20s
  cacheCleanupInterval: 12s
servers:
  example_server1:
    address: 192.168.1.152:27015
    rconPassword: XXX
  example_server2:
    address: 192.168.1.153:27015
    rconPassword: XXX
```

**Docker-Compose**

```
version: "3.3"
services:
  csgo-exporter:
    image: quay.io/galexrt/srcds_exporter:v1.4.3
    container_name: csgo-exporter
    command: ["/bin/srcds_exporter", "--config.file","/tmp/csgo/srcds.yaml", "--collectors.enabled","map,playercount,players"]
    network_mode: host
    volumes:
      - type: bind
        source: /srv/csgoexporter/config/srcds.yaml
        target: /tmp/csgo/srcds.yaml
```
